spring.application.name: Clarity

management:
  server.port: 9090
  endpoints.web.exposure.include: health,info,prometheus,beans,loggers

logging:
  level:
    clarity.ws: WARN

clarity:
  brokers:
    - host: localhost
