---
spring.application.name: Clarity

management:
  server.port: 9090
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    clarity.ws: WARN

clarity:
  brokers:
    - host: localhost

---
spring:
  config:
    activate:
      on-profile: demo
  rabbitmq:
    username: guest
    password: guest
