spring.application.name: Clarity

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,beans,loggers

logging:
  level:
    clarity.ws: WARN

clarity:
  brokers:
    - host: localhost
